### PR TITLE
Migrate project from .NET Core 3.0 to .NET Core 3.1

### PR DESCRIPTION
**Pull request by ranzeplay**

### CODE REVIEW

**Comment by pymart** [comment]
Hello.
It seems .net core 3.1.100 has bugs. for example when I wanted to add spaservices 3.1.0 to my project, I faced following errors: 
1- "Unable to resolve 'Microsoft.AspNetCore.SpaServices.Extensions (>= 3.1.0)' for '.NETCoreApp,Version=v3.1'."

2- "Package 'Microsoft.AspNetCore.SpaServices.Extensions' is incompatible with 'all' frameworks in project '......\ServerApp.csproj'"

**Comment by ranzeplay** [comment]
> Hello.
> It seems .net core 3.1.100 has bugs. for example when I wanted to add spaservices 3.1.0 to my project, I faced following errors:
> 1- "Unable to resolve 'Microsoft.AspNetCore.SpaServices.Extensions (>= 3.1.0)' for '.NETCoreApp,Version=v3.1'."
> 
> 2- "Package 'Microsoft.AspNetCore.SpaServices.Extensions' is incompatible with 'all' frameworks in project '......\ServerApp.csproj'"

Did you try to update all the frameworks to v3.1.0?

**Comment by pymart** [comment]
> > Hello.
> > It seems .net core 3.1.100 has bugs. for example when I wanted to add spaservices 3.1.0 to my project, I faced following errors:
> > 1- "Unable to resolve 'Microsoft.AspNetCore.SpaServices.Extensions (>= 3.1.0)' for '.NETCoreApp,Version=v3.1'."
> > 2- "Package 'Microsoft.AspNetCore.SpaServices.Extensions' is incompatible with 'all' frameworks in project '......\ServerApp.csproj'"
> 
> Did you try to update all the frameworks to v3.1.0?

I created a new project with .net core 3.1.100 with the following command:
dotnet new global json --sdk-version 3.1.100.
Then visual studio automatically added related frameworks to the project. After that when I Added spaservices v 3.1.0, I faced the error messages I mentioned before.

**Comment by ranzeplay** [comment]
So I need to revert to .NET Core 3.0? .NET Core 3.1 is not recommended this time?

**Pull request merged**
